name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
      -  run: gcc ultra.c -o ultra.exe
      - name: Run
      - run: ./ultra.exe
